### ISSUE TITLE
map address problem 

### ISSUE THREAD

**Issue by rut78HR** [spring-cloud-stream-app-starters/gpfdist#2]
Hello .. 
Is there a way to fix this on kubernetes v1.4.4  .. It maps to pods ip address instead of external? Is there way to provide external ip address for creating external table ?

2016-12-01 18:52:46.603 INFO 1 --- [io-8080-exec-10] o.a.kafka.common.utils.AppInfoParser : Kafka version : 0.10.1.0
2016-12-01 18:52:46.603 INFO 1 --- [io-8080-exec-10] o.a.kafka.common.utils.AppInfoParser : Kafka commitId : 3402a74efb23d1d4
2016-12-01 18:52:46.749 INFO 1 --- [io-8080-exec-10] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8888
2016-12-01 18:52:46.758 WARN 1 --- [io-8080-exec-10] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused; nested exception is java.net.ConnectException: Connection refused
2016-12-01 18:53:22.642 INFO 1 --- [TaskScheduler-1] o.s.b.f.xml.XmlBeanDefinitionReader : Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
2016-12-01 18:53:22.849 INFO 1 --- [TaskScheduler-1] o.s.jdbc.support.SQLErrorCodesFactory : SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase, Hana]
2016-12-01 18:53:22.949 ERROR 1 --- [TaskScheduler-1] o.s.c.s.a.g.sink.support.JdbcCommands : Error during run sql
org.springframework.dao.DataAccessResourceFailureException: StatementCallback; SQL [INSERT INTO httpdata SELECT * FROM httpdata_ext_90f5e4e4_d363_4ba2_aa01_2f55b73f7cf7]; ERROR: connection with gpfdist failed for gpfdist://10.36.0.27:8000/data. effective url: http://10.36.0.27:8000/data. error code = 110 (Connection timed out) (seg0 slice1 dbslave01:40000 pid=28847); nested exception is org.postgresql.util.PSQLException: ERROR: connection with gpfdist failed for gpfdist://10.36.0.27:8000/data. effective url: http://10.36.0.27:8000/data. error code = 110 (Connection timed out) (seg0 slice1 dbslave01:40000 pid=28847)
at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:105) ~[spring-jdbc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73) ~[spring-jdbc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]

**Comment by jvalkeal** [comment]
Unfortunately I think this is not possible at this moment. There's similar need for all apps which binds additional ports so most likely we get this sorted out at some point. Issue is more or less for apps to know their external address at a time of creation.
